In [3]:
%load_ext autoreload
%autoreload 2

In [48]:
def rotate_matrix_90_helper(m, sz):
    if sz <= 1:
        return
    
    s = (m.shape[0] - sz) // 2
    e = s + sz - 1
    
    t = np.copy(m[s, s:e])
    m[s, s:e] = m[s:e, e]
    m[s:e, e] = m[e, s+1:e+1][::-1]
    m[e, s+1:e+1] = m[s+1:e+1, s]
    m[s+1:e+1, s] = t[::-1]
    

def rotate_matrix_90(m):
    for sz in range(m.shape[0], 0, -2):
        rotate_matrix_90_helper(m, sz)
    return m

In [49]:
import numpy as np

sz = 3
m = np.arange(1, sz*sz+1)
m = m.reshape((sz, sz))
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [50]:
rotate_matrix_90(m)
m

array([[3, 6, 9],
       [2, 5, 8],
       [1, 4, 7]])

In [51]:
sz = 4
m = np.arange(1, sz*sz+1)
m = m.reshape((sz, sz))
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12],
       [13, 14, 15, 16]])

In [52]:
rotate_matrix_90(m)
m

array([[ 4,  8, 12, 16],
       [ 3,  7, 11, 15],
       [ 2,  6, 10, 14],
       [ 1,  5,  9, 13]])